travis:
  secure:
    BINSTAR_TOKEN: d2FnvJhHEcjl7OtS0jC4NaZ4Z2To2eMuXpJ39o9vkq3fDjsAsN2bu+LDDFmwQPRF4zI8u1q1lJiFtWVwshF6ocEuoSrMS6bnLnhY8uyub5LPAw0YxRh1OmWQMQEtmBQiGKhH+HLp1eWUVGnKd64RmkLcEit1qPOksC4GHmDuUr6QCSnlwuUm9UY04H0mrzW9DnNDJg4nPEb82TaY8ASGT4atCFw36IciFRniabchmyIvbu4Swi9HoMsneK5YvzTQ8QuI4u6qyn3agUNDCsyx1h5kp/o7jzg6klnEeYU5HXiq/6ELGSRYWh823q39iunmkREvrQPveUVLmScrHeMXUY1NmlaOZc2YmiPdxwk6iKiQwmAwO3Vhn5TWE9Q0vEdgCZe5Q+AKpyffrJiOT1vFK19zY18oiHyGd6nPyRadPHED+2qqdL8R5mbEux8r1bi6NdFX+x9XEsks86y+Vx0lqcSxVVsAQGfxRQwTZMvxlEatpBAW3s5fbZg22CBJLl+AKZBQ3VlXfH06T5shCPp6xEtO+91TNoGtlL8CjYvEQgeG6Cu4UXQMu5bH3AhtPFJHGb/3eUJcVW/+soUQ3BCW1YevHYu8gN4IlTYempTLq3UfZ3LHgqC2hJwvzKZ4WayV+wBEgwIOQmeNB08fuUAlT8AcwfKXrw6jnyiItLHBOm0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
