travis:
  secure:
    BINSTAR_TOKEN: nEtaIaPUXkEuzznveHcDh36frVjGRdg9uxw29FHS3SSqddOQV6p6P8itAxxKPAacgmHuWjgb5JnydhuKSmsZH6rD3p2O/vH4WQUL+HE4qdi/qY/+V4qrXmW8tWMYV5ONKjzBnOxwyMzla1P8uqhpJRdg3qpGfHwHUX4IngastBujuLgQ+Fg/15s3dbMUG7+kK9VC5P+sCW/2kRUEazKCW/VHweG2xPGoA1g92do49GRZXFSx+D7gCX+ItsW/wOZMRDxA/+UxYlraC9UKPPjm1ig5ZV3WsecRTcp2ZzLXXuYqHodt2do6gL4tlfh1sGRAF9wS1AK+mn6Y2gkdCnhptlumpa+vYz079EKVDR22o0z1+E7I07m+K4p10HW6Wid5Lc5Y+WU+Z6w81UizhyywjL8iEVw4qIpbvyo3TVLKurh3ENIzHSH6/gd9tYM1T3YG5Jhuahq+YG+y1pbOlNDebFhr2ely6powEcpbYNtMr/B9dHB1zkEkmAafHVeBTpZwqgqAi/VKYLy7GRJs6B0ik5rB6VO1YoShleekIRAzRYgzsq9HrrgFfduvpwxntLjV6BMTP7rD/J8SI+i7S/sdVtIybOMQWC9kn9gfgJA3USBRMGr2DxL2DJhuDFJPTHq3lPLF/7oQFW3MyIRgbUxTb9re/mAJpOTQGJxNLDBA7ok=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
